USE [master]
GO

/****** Object:  Database [TALPremiumInsurance]    Script Date: 01-10-2020 00:11:00 ******/
CREATE DATABASE [TALPremiumInsurance]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TALPremiumInsurance', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\TALPremiumInsurance.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'TALPremiumInsurance_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\TALPremiumInsurance_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [TALPremiumInsurance] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TALPremiumInsurance].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TALPremiumInsurance] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TALPremiumInsurance] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TALPremiumInsurance] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TALPremiumInsurance] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TALPremiumInsurance] SET ARITHABORT OFF 
GO

ALTER DATABASE [TALPremiumInsurance] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TALPremiumInsurance] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [TALPremiumInsurance] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TALPremiumInsurance] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TALPremiumInsurance] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TALPremiumInsurance] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TALPremiumInsurance] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TALPremiumInsurance] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TALPremiumInsurance] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TALPremiumInsurance] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TALPremiumInsurance] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TALPremiumInsurance] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TALPremiumInsurance] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TALPremiumInsurance] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TALPremiumInsurance] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TALPremiumInsurance] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TALPremiumInsurance] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TALPremiumInsurance] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TALPremiumInsurance] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [TALPremiumInsurance] SET  MULTI_USER 
GO

ALTER DATABASE [TALPremiumInsurance] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TALPremiumInsurance] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TALPremiumInsurance] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TALPremiumInsurance] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [TALPremiumInsurance] SET  READ_WRITE 
GO


