//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TALPremiumInsurance.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientPremium
    {
        public int ClientPremiumId { get; set; }
        public string Name { get; set; }
        public int Age { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public int OccupationId { get; set; }
        public decimal DeathSumInsured { get; set; }
        public decimal MonthlyPremium { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Occupation Occupation { get; set; }
    }
}
