//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TALPremiumInsurance.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class OccupationRating
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OccupationRating()
        {
            this.Occupations = new HashSet<Occupation>();
        }
    
        public int OccupationRatingId { get; set; }
        public string Rating { get; set; }
        public decimal Factor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Occupation> Occupations { get; set; }
    }
}
